version: '3.0'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - .:/app
    networks:
      - vue-app
networks:
  vue-app:
    driver: bridge